---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  LITELLM_BASE_URL: {{ .Values.secret.litellmBaseUrl | b64enc | quote }}
  LITELLM_API_KEY: {{ .Values.secret.litellmApiKey | b64enc | quote }}
