---
apiVersion: v1
kind: Service
metadata:
  name: litellm-mcp-server
  namespace: mcp
  labels:
   app: litellm-mcp-server           
spec:
  selector:
    app: litellm-mcp-server       
  ports:
    - name: http
      protocol: TCP              
      port: 8000                 
      targetPort: 8000
  type: ClusterIP